# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95383eeed87ec6296d34a20aae11bdefaf8b73798bd3f41d824ca1047b11eda033a79a815fbf840ee2f18201c928b03549e5e671c2769f56145667d7d2a39313

test:
  secret_key_base: 4de8d3979af9f9d974812abdb2309bfa1787cf1474559ef68186cf12529f106f163c39c739fb0f721426a62680a59ca55e8b51ee08811ab22e1cfdc1f6855053

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
